### ISSUE TITLE
Post and patch trip comments problem.

### ISSUE THREAD

**Issue by krzysztofMi** [projekt-zespolowy-lab04-2020/backend#28]
According to this:

![obraz](https://user-images.githubusercontent.com/56334537/79743641-36760200-8305-11ea-9b0c-44d512c96c80.png)

all users should be able to create comments to trip. Now only trip creator can do it.
Also problem is with patch trip comments. Admin can't modify them.

**Comment by marcinpiwko** [comment]
Resolved
