### ISSUE TITLE
The ticket ID should be available in the response

### ISSUE THREAD

**Issue by sebapaszynski** [projekt-zespolowy-lab04-2020/backend#36]
Currently, when we create a ticket in response, only content is available. No content is needed here, the ticket **id** would be more useful. I suggest choosing one of the two solutions:

<pre>
<b>1</b>
{
  "id": 0,
  "content": "string"
}
</pre>

<pre>
<b>2</b>
{
  "id": 0,
}
</pre>

**Comment by kotcrab** [comment]
:+1:

We can probably just reuse the model for get tickets
```
  {
    "id": 0,
    "closed": true,
    "author": "string",
    "create_date": "string",
    "content": "string"
  }
```

**Comment by sebapaszynski** [comment]
Yep, That would be the best solution🏆

**Comment by kotcrab** [comment]
Done in #37
