### ISSUE TITLE
Adding the author to the returned comment

### ISSUE THREAD

**Issue by sebapaszynski** [projekt-zespolowy-lab04-2020/backend#38]
I would like a response from the server to include the author: 

<pre>
{
   "content":"string",
   <b>"author":{
      "firstName":"string",
      "lastName":"string"
   }<b>
}
</pre>

**Comment by kotcrab** [comment]
Which endpoint is this?

**Comment by sebapaszynski** [comment]
Ticket 
<pre>POST/ticket/{ticketId}/comment Create new comment</pre>
I would also like the author not to be an email address, but instead I would like to get the firstName and lastName or the entire user object.

**Comment by kotcrab** [comment]
> entire user object

Let's go with this

**Comment by krzysztofMi** [comment]
Done #39
