### ISSUE TITLE
Api.yaml trips references problem.

### ISSUE THREAD

**Issue by krzysztofMi** [projekt-zespolowy-lab04-2020/backend#40]
In api.yaml file there are some references to trips with are not further implemented in document.
Those are:
   * "#/components/schemas/Trips"
   * "#/components/schemas/PatchTrip"
   * "#/components/schemas/NewTrip"

![obraz](https://user-images.githubusercontent.com/56334537/80591465-0a056880-8a1e-11ea-9dfa-11213b477941.png)

Someone who worked on trips endpoint can implemented them for practice ;D

**Comment by kotcrab** [comment]
Covered by #30
