### ISSUE TITLE
POST /trips/{tripId}/comments

### ISSUE THREAD

**Issue by sebapaszynski** [projekt-zespolowy-lab04-2020/backend#59]
**POST /trips/{tripId}/comments** should return resposne in the same format as **POST
/tickets/{ticketId}/comments** . Now only status is returned.
<pre>
{
  "content": "string",
  "author": {
    "firstName": "string",
    "lastName": "string",
    "email": "string",
    "disabled": true,
    "roles": [
      "string"
    ],
    "createDate": "string"
  }
}
</pre>
Additionally the status code in both cases should be the same either 204 or 200 and now it is different.

**Comment by marcinpiwko** [comment]
Fixed
